import { MantineThemeOverride } from "@mantine/core";
import rubik from "../fonts/rubik.font";

// The app's one brand accent — every button/link/badge across the site
// derives from this single hex value. Used to be admin-configurable at
// runtime (color picker + custom-hex override in Admin → Appearance); now
// that the whole visual identity is code-driven, changing the accent is a
// one-line edit here instead of a database row, shipped through the normal
// build/deploy path like everything else.
const ACCENT_HEX = "#ff7a00";

const hexToRgb = (hex: string): { r: number; g: number; b: number } => ({
  r: parseInt(hex.slice(1, 3), 16),
  g: parseInt(hex.slice(3, 5), 16),
  b: parseInt(hex.slice(5, 7), 16),
});

const rgbToHex = (r: number, g: number, b: number): string =>
  `#${[r, g, b]
    .map((channel) =>
      Math.min(255, Math.max(0, Math.round(channel)))
        .toString(16)
        .padStart(2, "0"),
    )
    .join("")}`;

const mixHexColors = (
  baseHex: string,
  mixHex: string,
  weight: number,
): string => {
  const base = hexToRgb(baseHex);
  const mix = hexToRgb(mixHex);
  const inverseWeight = 1 - weight;

  return rgbToHex(
    base.r * inverseWeight + mix.r * weight,
    base.g * inverseWeight + mix.g * weight,
    base.b * inverseWeight + mix.b * weight,
  );
};

// Mantine wants 10 shades (light-to-dark) for a color to work as
// `primaryColor` — generated by blending the accent toward white (lighter
// shades) and black (darker shades), the same recipe the old runtime admin
// theme builder used, just computed once here instead of per-request.
const createMantineScaleFromHex = (hex: string) =>
  [
    mixHexColors(hex, "#ffffff", 0.92),
    mixHexColors(hex, "#ffffff", 0.82),
    mixHexColors(hex, "#ffffff", 0.68),
    mixHexColors(hex, "#ffffff", 0.54),
    mixHexColors(hex, "#ffffff", 0.36),
    hex,
    mixHexColors(hex, "#000000", 0.1),
    mixHexColors(hex, "#000000", 0.22),
    mixHexColors(hex, "#000000", 0.34),
    mixHexColors(hex, "#000000", 0.46),
  ] as [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ];

export default <MantineThemeOverride>{
  fontFamily: `${rubik.style.fontFamily}, -apple-system, BlinkMacSystemFont, system-ui, sans-serif`,
  colors: {
    accent: createMantineScaleFromHex(ACCENT_HEX),
    dark: [
      "#C1C2C5",
      "#A6A7AB",
      "#909296",
      "#5C5F66",
      "#2E2E2E",
      "#1F1F1F",
      "#141414",
      "#050505",
      "#030303",
      "#000000",
    ],
  },
  primaryColor: "accent",
  defaultRadius: "md",
  components: {
    Modal: {
      styles: (theme) => ({
        title: {
          fontSize: theme.fontSizes.lg,
          fontWeight: 700,
        },
      }),
    },
    // The navbar's own dropdowns (avatar menu, share-links menu) render via
    // Mantine's ModalsProvider-style portal too, so — same reasoning as
    // glassModalStyles — they never pick up the header's local translucent
    // styling just by sitting under it; without this they show this app's
    // near-black `dark` palette (see above) as a flat, sharp-cornered box
    // that reads as leftover default chrome against everything else's
    // liquid-glass surfaces. Blur/border/shadow reuse glassModalStyles'
    // recipe, but the background is a flat tint rather than that recipe's
    // diagonal 3-stop gradient: a gradient's stops are percentages of the
    // element's own diagonal, so the exact same recipe that reads as a
    // soft, gradual sheen across a ~500px modal compresses into a short,
    // hard-edged dark smear on a menu that's only ~150px across — worse
    // the smaller the menu. A flat fill has no such stop math to break.
    Menu: {
      styles: (theme) => {
        const dark = theme.colorScheme === "dark";
        return {
          dropdown: {
            backgroundColor: dark
              ? "rgba(18, 18, 18, 0.6)"
              : "rgba(255, 255, 255, 0.55)",
            backdropFilter: "blur(22px) saturate(160%)",
            WebkitBackdropFilter: "blur(22px) saturate(160%)",
            border: `1px solid ${dark ? "rgba(255, 255, 255, 0.2)" : "rgba(255, 255, 255, 0.5)"}`,
            boxShadow: dark
              ? "0 24px 60px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.2)"
              : "0 24px 60px rgba(0, 0, 0, 0.18), inset 0 1px 0 rgba(255, 255, 255, 0.7)",
          },
          item: {
            color: dark ? theme.white : theme.black,
            "&:hover": {
              backgroundColor: dark
                ? "rgba(255, 255, 255, 0.1)"
                : "rgba(255, 255, 255, 0.35)",
            },
          },
          itemIcon: {
            color: dark ? "rgba(255, 255, 255, 0.7)" : "rgba(0, 0, 0, 0.6)",
          },
          divider: {
            borderColor: dark
              ? "rgba(255, 255, 255, 0.12)"
              : "rgba(0, 0, 0, 0.1)",
          },
          label: {
            color: dark ? "rgba(255, 255, 255, 0.5)" : "rgba(0, 0, 0, 0.45)",
          },
        };
      },
    },
    // Mantine's built-in disabled-button colors (dark[4] bg / dark[6] text)
    // assume its own default dark palette. This app's "dark" scale is
    // redefined much closer to near-black for the branding, which collapses
    // those two shades to near-identical grays — a disabled button read as
    // indistinguishable from an enabled one. A light-grey chip (rather than
    // a dark one) reads clearly as "off" against this app's near-black
    // surroundings in both color schemes.
    Button: {
      styles: (theme) => ({
        root: {
          "&:disabled, &[data-disabled]": {
            opacity: 1,
            backgroundColor: theme.colors.gray[3],
            color: theme.colors.gray[7],
            border: "none",
          },
        },
      }),
    },
    // Toasts (upload errors, admin confirmations, etc.) render via the one
    // global <Notifications/> portal in _app.tsx, so — unlike Menu above,
    // which needs repeating inside every nested glass provider — a single
    // override here reaches every toast in the app. Left the plain,
    // opaque Mantine default (solid dark[6]/white fill, theme.shadows.lg)
    // the one glass surface in the app that didn't match the rest.
    Notification: {
      styles: (theme) => {
        const dark = theme.colorScheme === "dark";
        return {
          root: {
            backgroundColor: dark
              ? "rgba(18, 18, 18, 0.6)"
              : "rgba(255, 255, 255, 0.55)",
            backdropFilter: "blur(22px) saturate(160%)",
            WebkitBackdropFilter: "blur(22px) saturate(160%)",
            border: `1px solid ${dark ? "rgba(255, 255, 255, 0.2)" : "rgba(255, 255, 255, 0.5)"}`,
            boxShadow: dark
              ? "0 24px 60px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.2)"
              : "0 24px 60px rgba(0, 0, 0, 0.18), inset 0 1px 0 rgba(255, 255, 255, 0.7)",
          },
          // The status icon (red ✕ / green ✓) already carries its own
          // solid-filled circle — that's the color cue, so it's left
          // alone. Title/description are the only other text riding on
          // the now-translucent root, so they get the same halo the rest
          // of the app's glass surfaces use for legibility over whatever
          // happens to be behind them.
          title: {
            textShadow: dark
              ? "0 1px 3px rgba(0, 0, 0, 0.7)"
              : "0 1px 3px rgba(255, 255, 255, 0.7)",
          },
          description: {
            textShadow: dark
              ? "0 1px 3px rgba(0, 0, 0, 0.7)"
              : "0 1px 3px rgba(255, 255, 255, 0.7)",
          },
        };
      },
    },
  },
};
